# Generated by Django 5.2.16 on 2026-07-09 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiles_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('non_binary', 'Non-binary'), ('other', 'Other'), ('unset', 'Unset')], default='unset', max_length=32)),
                ('sexual_preference', models.CharField(choices=[('heterosexual', 'Heterosexual'), ('homosexual', 'Homosexual'), ('bisexual', 'Bisexual'), ('pansexual', 'Pansexual'), ('asexual', 'Asexual'), ('unset', 'Unset')], default='bisexual', max_length=32)),
                ('biography', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('location_source', models.CharField(choices=[('gps', 'GPS'), ('manual', 'Manual'), ('mixed', 'Mixed')], default='manual', max_length=16)),
                ('fame_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fame_rating_components', models.JSONField(blank=True, default=dict)),
                ('fame_rating_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_profile',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tag')),
            ],
            options={
                'db_table': 'profiles_profile_tag',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(related_name='profiles', through='profiles.ProfileTag', to='profiles.tag'),
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profiles/pictures/')),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='profiles.profile')),
            ],
            options={
                'db_table': 'profiles_profile_picture',
                'ordering': ['position', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'position'), name='unique_profile_picture_position'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('profile',), name='unique_primary_picture_per_profile')],
            },
        ),
        migrations.AddConstraint(
            model_name='profiletag',
            constraint=models.UniqueConstraint(fields=('profile', 'tag'), name='unique_profile_tag'),
        ),
    ]
